config/routes.rb
Rails.application.routes.draw do
  namespace :manage do
    get 'venues/index'
  end

  get '/blog' => redirect('http://blog.venuecenter.com')
  get '/tx/austin/www.WallerBallroom.com' => redirect('https://venuecenter.com/tx/austin/waller-ballroom')
  get '/tx/friendswood/friendswood-mediation-conference-center', to: redirect('/')
  get '/venues/friendswood-mediation-conference-center', to: redirect('/')

  mount StripeEvent::Engine => '/stripe-events'

  get 'concierge/index'
  get 'lists/:id' => 'account/lists#show'
  get 'new_search' => 'new_search#index', as: 'new-search'

  resources :vendors
  match '/administrator/index.php', via: %i[get post], to: redirect('/')
  get '/users/login?:data', to: redirect('/users/login')
  get '/users/sign-up?:data', to: redirect('/users/sign-up')
  get '/blog', to: redirect('http://blog.venuecenter.com')
  get '/blog/robots.txt', to: redirect('http://blog.venuecenter.com/robots.txt')
  get '/blog/:category/:name', to: redirect('http://blog.venuecenter.com')

  get '/xmlrpc.php', to: redirect('/')
  get '/index.php', to: redirect('/')
  get '/index.php/venues', to: redirect('/')
  get '/cdn-cgi/l', to: redirect('/')
  get '/plugins/system/jch_optimize/assets2/jscss.php', to: redirect('/')
  get '/users/how-it-works', to: redirect('/how-it-works')
  get '/corporate-party-venues/tx/dallas', to: redirect('/corporate-event-venues/tx/dallas')

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/payments/payment', to: 'payments#payment', as: 'paymentspayment', via: [:get]
  match '/payments/relay_response', to: 'payments#relay_response', as: 'payments_relay_response', via: [:post]
  match '/payments/receipt', to: 'payments#receipt', as: 'payments_receipt', via: [:get]

  get '/cities' => 'cities#index', as: :cities_home

  get '/venue-manager' => 'biz#index', as: :biz_home
  get '/biz', to: redirect('/venue-manager')
  match 'biz/search' => 'biz#search', via: %i[get post], as: :biz_search
  get 'biz/new' => 'biz#new'
  post 'biz/create' => 'biz#create'
  get 'biz/claim/:id' => 'biz#claim', as: :biz_claim
  patch 'biz/update/:id' => 'biz#update'
  put 'biz/update/:id' => 'biz#update'
  get 'biz/select-plan/:id' => 'biz#selectplan', as: :biz_select_plan
  get 'biz/checkout' => 'biz#checkout'
  match 'biz/process-checkout' => 'biz#process_checkout', via: %i[get post]
  post 'biz/relay_response' => 'biz#relay_response', as: :biz_relay_response
  match 'biz/receipt' => 'biz#receipt', via: %i[get post], as: :biz_receipt

  namespace :backoffice do
    resources :venues
    resources :events
    resources :rfps
    resources :users
  end

  namespace :manage do
    get 'venues' => 'venues#index', as: :venues
    get 'details' => 'details#index', as: :details
    get 'details/general' => 'details#general'
    put 'details/general/update' => 'details#update_general'
    patch 'details/general/update' => 'details#update_general'
    get 'details/categories' => 'details#categories'
    put 'details/categoris/update' => 'details#update_categories'
    patch 'details/categories/update' => 'details#update_categories'
    get 'details/features' => 'details#features'
    put 'details/features/update' => 'details#update_features'
    patch 'details/features/update' => 'details#update_features'
    get 'details/photos' => 'details#photos'
    post 'details/photos/new' => 'details#new_photos'
    put 'details/header-photo/update' => 'details#update_header_photo'
    patch 'details/header-photo/update' => 'details#update_header_photo'
    get 'details/directions' => 'details#directions'
    put 'details/directions/update' => 'details#update_directions'
    patch 'details/directions/update' => 'details#update_directions'
    get 'details/spaces' => 'spaces#index'
    put 'details/spaces/edit/:id' => 'spaces#edit'
    patch 'details/spaces/update' => 'spaces#update'
    resources :rfps
    resources :reviews
    get 'billing' => 'billing#index', as: :billing
    get 'data/yelp' => 'data#yelp'
  end

  get 'manage' => 'manage#index', as: :manage_home

  devise_for :admin, path: 'biz', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: '/profile/edit' }, controllers: { sessions: 'biz/sessions',
                                                                                                                                                   registrations: 'biz/registrations', passwords: 'biz/passwords' }
  namespace :admin do
    get 'user-events' => 'data#userevents'
    get 'yelp' => 'data#yelp', as: :get_yelp_data
    get 'yelp2' => 'data#yelp2'
    get 'foursquare' => 'data#foursquare', as: :get_foursquare_data
    get 'events' => 'data#events'
    get 'venue-categories' => 'data#categories'
    resources :rfp
    resources :reviews
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign-up', edit: '/account/profile/edit' }, controllers: { sessions: 'sessions', registrations: 'registrations',
                                                                                                                                             omniauth_callbacks: 'omniauth_callbacks' }
  get '/users/register', to: redirect('users/sign-up')

  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], as: :finish_signup

  namespace :account do
    get 'profile' => 'profile#index', as: :profile
    resources :reviews
    resources :rfps
    get 'rfps/:venue_id/new', to: 'rfps#new', as: :new_rfp
    get 'rfps/:id/confirmation', to: 'rfps#confirmation', as: :rfp_confirmation
    resources :events
    resources :venues
    resources :lists
    post 'venues/new' => 'venues#new', as: :save_venue
    get 'profile/cancel_account' => 'profile#cancel_account', as: :cancel
  end
  get '/corporate-venues/tx/Austin', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Austin')
  get '/corporate-venues/tx/Dallas', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Dallas')
  get '/party-venues/tx/Dallas', to: redirect('http://venuecenter.com/adult-birthday-party-venues/tx/Dallas')
  get '/corporate-venues/tx/houston', to: redirect('http://venuecenter.com/corporate-event-venues/tx/houston')
  get '/corporate-venues/tx/Houston', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Houston')
  get '/corporate-party-venues/tx/Austin', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Austin')
  get '/corporate-party-venues/tx/Dallas', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Dallas')
  get '/corporate-party-venues/tx/Houston', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Houston')
  get '/event-venues/:state/:city' => 'search#index', as: :city_search
  get '/:event_type-venues/:state/:city' => 'search#index', as: :event_type_search
  get '/tx/houston', to: redirect('/event-venues/tx/houston')
  get '/tx/dallas', to: redirect('/event-venues/tx/dallas')
  get '/tx/austin', to: redirect('/event-venues/tx/austin')
  get '/tx/fort-worth', to: redirect('/event-venues/tx/fort-worth')
  get '/event/:state/:city', to: redirect('/event-venues/%{state}/%{city}')
  get '/cities/:state/:city' => 'search#index'
  get '/search/confirm-submit' => 'search#confirm_submit'
  post '/search/get-info' => 'search#get_info', as: :search_get_info

  match '/search/:loc' => 'search#index', via: %i[get post], as: :search_loc
  match '/search' => 'search#index', via: %i[get post], as: :search

  resources :states

  get 'account' => 'account#index', as: :account_home

  get 'concierge' => 'concierge#index', as: :concierge_home
  get ':state/:city/:slug' => 'venue#index', as: :venue
  get 'venues/:slug' => 'venue#index', as: :old_venue
  get 'venues/not-found' => 'venue#not_found', as: :venue_not_found
  get 'about' => 'home#about'
  get 'how-it-works' => 'home#works'
  get 'faq' => 'home#faq'
  get 'contact' => 'home#contact'
  get 'tos' => 'home#tos'
  get 'privacy' => 'home#privacy'
  match 'process-contact' => 'home#processcontact', via: %i[get post]

  root 'home#index', as: :home

end

app/models/venue.rb
require 'elasticsearch/model'

class Venue < ActiveRecord::Base
  extend FriendlyId

  friendly_id :slug_candidates, use: :slugged
  after_create :remake_slug

  # searchkick callbacks: :async, locations: ["location"]

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  include Impressionist::IsImpressionable

  def slug_candidates
    [
      :name,
      %i[name city],
      %i[name address city]
    ]
  end

  def remake_slug
    update_attribute(:slug, nil)
    save!
  end

  def should_generate_new_friendly_id?
    new_record? || slug.nil?
  end

  belongs_to :state
  belongs_to :billing_plan
  belongs_to :venue_capacity

  has_many :venue_spaces, dependent: :destroy
  has_many :rfps, dependent: :destroy
  has_many :venue_reviews, dependent: :destroy
  has_many :venue_images, dependent: :destroy
  has_and_belongs_to_many :admins
  has_many :venue_transactions
  has_many :venue_packages, dependent: :destroy
  has_many :user_saved_venues, dependent: :destroy
  has_and_belongs_to_many :venue_types

  has_many :venue_event_types, dependent: :destroy
  has_many :event_types, through: :venue_event_types

  mount_uploader :main_image, MainImageUploader

  has_many :user_list_venues
  has_many :user_lists, through: :user_list_venues

  has_many :venue_staff, dependent: :destroy

  accepts_nested_attributes_for :venue_packages, allow_destroy: true
  accepts_nested_attributes_for :venue_spaces, allow_destroy: true
  accepts_nested_attributes_for :venue_staff, allow_destroy: true
  accepts_nested_attributes_for :venue_types, allow_destroy: true
  accepts_nested_attributes_for :venue_event_types, allow_destroy: true

  is_impressionable counter_cache: true, column_name: :pageviews, unique: %i[impressionable_type impressionable_id session_hash]

  # validates_presence_of :name, :address, :city, :state_id, :billing_plan_id
  # validates_uniqueness_of :name, scope: [:address, :city, :state], message: 'Venue has already been taken'
  # validates_uniqueness_of :stripe_customer_id

  geocoded_by :full_address, latitude: :lat, longitude: :lng

  after_validation :geocode # , :if => :address_changed?

  def full_address
    [address, city, state].compact.join(', ')
  end

  def search_data
    attributes.merge location: [lat, lng]
  end
end

# Venue.import

app/models/venue_type.rb
class VenueType < ActiveRecord::Base
  has_and_belongs_to_many :venues, dependent: :destroy
  validates_presence_of :name
end

app/controllers/account/venues_controller.rb
class Account::VenuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @venues = UserSavedVenue.where('user_id = ?', current_user.id).paginate(page: params[:page], per_page: 20)
  end

  def new
    @sv = UserSavedVenue.new
    @sv.user_id = current_user.id
    @sv.venue_id = params[:venue_id]
    if @sv.save
      redirect_to :back, notice: 'Venue was saved.'
    else
      render :back
    end
  end

  def destroy
    @venue = UserSavedVenue.find(params[:id])
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to '/account/venues', notice: 'Saved venue was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # def user_saved_venue_params
  # params.require(:user_saved_venue).permit(:user_id, :venue_id, :user_event_id)
  # end
end

app/controllers/backoffice/events_controller.rb
class Backoffice::EventsController < ApplicationController
  def index; end

  def new; end

  def create; end

  def edit; end

  def update; end
end

app/controllers/backoffice/rfps_controller.rb
class Backoffice::RfpsController < ApplicationController
  def destroy
    @rfp = Rfp.find(params[:id])
    @rfp.destroy

    redirect_to :back
  end
end

app/controllers/backoffice/users_controller.rb
class Backoffice::UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 25)
  end

  def show
    @user = User.find(params[:id])
    @rfps = Rfp.where('user_id=?', params[:id])
  end
end

app/controllers/backoffice/venues_controller.rb
class Backoffice::VenuesController < ApplicationController
  def index
    @venues = Venue.paginate(page: params[:page], per_page: 25).order(pageviews: :desc)
  end

  def show
    @venue = Venue.friendly.find(params[:id])
    @admins = Admin.where('active_venue_id = ?', @venue.id)
    @rfps = Rfp.where('venue_id=?', @venue.id)
  end

  def new; end

  def create; end

  def edit; end

  def update; end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
end

app/controllers/venue_controller.rb
class VenueController < ApplicationController
  def index
    @venue = Venue.friendly.find(params[:slug])

    # Handle venue not found
    if @venue.nil?
      flash[:notice] = 'The venue you tried to access was not found'
      redirect_to home_path
    else
      impressionist(@venue) if Rails.env.production?

      unless session['search_id'].blank?
        @search = VenueSearch.find(session['search_id'])
        @search_info = JSON.parse(@search.search_options)
      end
      @reviews = VenueReview.select('*').joins(:user).where('venue_reviews.venue_id = ? && users.deleted_at IS NULL', @venue.id).order(created_at: :desc)

      @review = VenueReview.new

      @rfp = Rfp.new

      @venue_images = VenueImage.where('venue_id = ?', @venue.id)
      @total_reviews = @reviews.count

      @spaces = VenueSpace.where('venue_id = ?', @venue.id)

      if @venue.billing_plan_id == 1 || @venue.billing_plan_id == 4
        @nearby_venues = Venue.near(@venue, 10).where('venue_capacity_id >= ?', @venue.venue_capacity_id).limit(6).offset(1).order('billing_plan_id desc')
      end
      # if !@venue.yelp_id.blank?
      #   #begin
      #     @yelp_data = Yelp.client.business(URI.escape(@venue.yelp_id))
      #   #rescue
      #     if @yelp_data.nil?
      #       @yr = 0
      #     elsif @yelp_data.review_count > 3
      #       @yr = 3
      #     else
      #       @yr = @yelp_data.review_count
      #     end
      #     @total_reviews = @total_reviews + @yr
      #   #end
      # end

      if user_signed_in?
        @saved = UserSavedVenue.where('user_id = ? && venue_id = ?', current_user.id, @venue.id)
      end
    end
  end

  rescue_from ActiveRecord::RecordNotFound do
    render :not_found
  end
end

app/helpers/account/venues_helper.rb
module Account::VenuesHelper
end

app/helpers/backoffice/events_helper.rb
module Backoffice::EventsHelper
end

app/helpers/backoffice/rfp_helper.rb
module Backoffice::RfpHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/helpers/backoffice/venues_helper.rb
module Backoffice::VenuesHelper
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/helpers/venue_helper.rb
module VenueHelper
end

app/views/backoffice/venues/index.html.erb
<div class="container-fluid" style="margin-top: 20px;">
  <div class="row">
    <div class="col-sm-12">
      <h1>Venues</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Venue</th>
            <th>Billing Plan</th>
            <th>Status</th>
            <th>Location</th>
            <th>Categories</th>
            <th>Pageviews</th>
            <th>Admins</th>
            <th>Total RFPs</th>
          </tr>
        </thead>
        <tbody>
          <% @venues.each do |venue| %>
            <tr>
              <td><%= link_to venue.name, backoffice_venue_path(venue) %></td>
              <td><%= venue.billing_plan.name %></td>
              <td><%= venue.status %></td>
              <td><%= venue.city %>, <%= venue.state.abbrev %></td>
              <td><%= venue.venue_types.map(&:name).sort.join(", ") %></td>
              <td><%= venue.pageviews %></td>
              <td><%= venue.admins.count %></td>
              <td><%= venue.rfps.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @venues %>
    </div><!-- .col s12 -->
  </div><!-- .row -->
</div> <!-- .container -->

app/views/backoffice/venues/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div style="margin: 20px 0;">
        <%= link_to '<< Back to Venues', backoffice_venues_path %>
      </div>

      <h1><%= @venue.name %></h1>
    </div><!-- col-sm-12 -->
  </div><!-- .row -->
  <div class="row">
    <div class="col-sm-12">
      <h2>Admins <small>(<%= @admins.count() %>)</small></h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Title</th>
            <th>Email</th>
            <th>Created At</th>
            <th>Last Login</th>
          </tr>
        </thead>
        <tbody>
          <% @admins.each do |a| %>
            <tr>
              <td><%= a.first_name %> <%= a.last_name %></td>
              <td><%= a.title %></td>
              <td><%= a.email %></td>
              <td><%= a.created_at %></td>
              <td><%= a.last_sign_in_at %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!-- col-sm-12 -->
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h2>RFPs <small>(<%= @rfps.count() %>)</small></h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Date Added</th>
            <th>Event Type</th>
            <th>Event Date</th>
            <th>Customer</th>
            <th>Guests</th>
            <th>Budget</th>
            <th>Hotel?</th>
            <th>Flight?</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @rfps.each do |rfp| %>
            <tr>
              <td><%= rfp.id %></td>
              <td><%= rfp.created_at %></td>
              <td><%= rfp.event_type.name %></td>
              <td><%= rfp.desired_date %></td>
              <td><%= rfp.first_name %> <%= rfp.last_name %></td>
              <td><%= rfp.num_guests %></td>
              <td><%= rfp.max_budget %></td>
              <td><%= rfp.need_flight %></td>
              <td><%= rfp.overnight_needed %></td>
              <td>
                <%= rfp.external_rfp_status.name %><br>
                <%= rfp.rfp_status.name %>
              </td>
              <td>
                <%= link_to("Delete", backoffice_rfp_path(rfp), method: :delete, remote: true, data: { confirm: 'Are you sure?'} ) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div><!-- .row -->
</div><!-- .container -->