config/routes.rb
Rails.application.routes.draw do
  namespace :manage do
    get 'venues/index'
  end

  get '/blog' => redirect('http://blog.venuecenter.com')
  get '/tx/austin/www.WallerBallroom.com' => redirect('https://venuecenter.com/tx/austin/waller-ballroom')
  get '/tx/friendswood/friendswood-mediation-conference-center', to: redirect('/')
  get '/venues/friendswood-mediation-conference-center', to: redirect('/')

  mount StripeEvent::Engine => '/stripe-events'

  get 'concierge/index'
  get 'lists/:id' => 'account/lists#show'
  get 'new_search' => 'new_search#index', as: 'new-search'

  resources :vendors
  match '/administrator/index.php', via: %i[get post], to: redirect('/')
  get '/users/login?:data', to: redirect('/users/login')
  get '/users/sign-up?:data', to: redirect('/users/sign-up')
  get '/blog', to: redirect('http://blog.venuecenter.com')
  get '/blog/robots.txt', to: redirect('http://blog.venuecenter.com/robots.txt')
  get '/blog/:category/:name', to: redirect('http://blog.venuecenter.com')

  get '/xmlrpc.php', to: redirect('/')
  get '/index.php', to: redirect('/')
  get '/index.php/venues', to: redirect('/')
  get '/cdn-cgi/l', to: redirect('/')
  get '/plugins/system/jch_optimize/assets2/jscss.php', to: redirect('/')
  get '/users/how-it-works', to: redirect('/how-it-works')
  get '/corporate-party-venues/tx/dallas', to: redirect('/corporate-event-venues/tx/dallas')

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/payments/payment', to: 'payments#payment', as: 'paymentspayment', via: [:get]
  match '/payments/relay_response', to: 'payments#relay_response', as: 'payments_relay_response', via: [:post]
  match '/payments/receipt', to: 'payments#receipt', as: 'payments_receipt', via: [:get]

  get '/cities' => 'cities#index', as: :cities_home

  get '/venue-manager' => 'biz#index', as: :biz_home
  get '/biz', to: redirect('/venue-manager')
  match 'biz/search' => 'biz#search', via: %i[get post], as: :biz_search
  get 'biz/new' => 'biz#new'
  post 'biz/create' => 'biz#create'
  get 'biz/claim/:id' => 'biz#claim', as: :biz_claim
  patch 'biz/update/:id' => 'biz#update'
  put 'biz/update/:id' => 'biz#update'
  get 'biz/select-plan/:id' => 'biz#selectplan', as: :biz_select_plan
  get 'biz/checkout' => 'biz#checkout'
  match 'biz/process-checkout' => 'biz#process_checkout', via: %i[get post]
  post 'biz/relay_response' => 'biz#relay_response', as: :biz_relay_response
  match 'biz/receipt' => 'biz#receipt', via: %i[get post], as: :biz_receipt

  namespace :backoffice do
    resources :venues
    resources :events
    resources :rfps
    resources :users
  end

  namespace :manage do
    get 'venues' => 'venues#index', as: :venues
    get 'details' => 'details#index', as: :details
    get 'details/general' => 'details#general'
    put 'details/general/update' => 'details#update_general'
    patch 'details/general/update' => 'details#update_general'
    get 'details/categories' => 'details#categories'
    put 'details/categoris/update' => 'details#update_categories'
    patch 'details/categories/update' => 'details#update_categories'
    get 'details/features' => 'details#features'
    put 'details/features/update' => 'details#update_features'
    patch 'details/features/update' => 'details#update_features'
    get 'details/photos' => 'details#photos'
    post 'details/photos/new' => 'details#new_photos'
    put 'details/header-photo/update' => 'details#update_header_photo'
    patch 'details/header-photo/update' => 'details#update_header_photo'
    get 'details/directions' => 'details#directions'
    put 'details/directions/update' => 'details#update_directions'
    patch 'details/directions/update' => 'details#update_directions'
    get 'details/spaces' => 'spaces#index'
    put 'details/spaces/edit/:id' => 'spaces#edit'
    patch 'details/spaces/update' => 'spaces#update'
    resources :rfps
    resources :reviews
    get 'billing' => 'billing#index', as: :billing
    get 'data/yelp' => 'data#yelp'
  end

  get 'manage' => 'manage#index', as: :manage_home

  devise_for :admin, path: 'biz', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: '/profile/edit' }, controllers: { sessions: 'biz/sessions',
                                                                                                                                                   registrations: 'biz/registrations', passwords: 'biz/passwords' }
  namespace :admin do
    get 'user-events' => 'data#userevents'
    get 'yelp' => 'data#yelp', as: :get_yelp_data
    get 'yelp2' => 'data#yelp2'
    get 'foursquare' => 'data#foursquare', as: :get_foursquare_data
    get 'events' => 'data#events'
    get 'venue-categories' => 'data#categories'
    resources :rfp
    resources :reviews
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign-up', edit: '/account/profile/edit' }, controllers: { sessions: 'sessions', registrations: 'registrations',
                                                                                                                                             omniauth_callbacks: 'omniauth_callbacks' }
  get '/users/register', to: redirect('users/sign-up')

  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], as: :finish_signup

  namespace :account do
    get 'profile' => 'profile#index', as: :profile
    resources :reviews
    resources :rfps
    get 'rfps/:venue_id/new', to: 'rfps#new', as: :new_rfp
    get 'rfps/:id/confirmation', to: 'rfps#confirmation', as: :rfp_confirmation
    resources :events
    resources :venues
    resources :lists
    post 'venues/new' => 'venues#new', as: :save_venue
    get 'profile/cancel_account' => 'profile#cancel_account', as: :cancel
  end
  get '/corporate-venues/tx/Austin', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Austin')
  get '/corporate-venues/tx/Dallas', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Dallas')
  get '/party-venues/tx/Dallas', to: redirect('http://venuecenter.com/adult-birthday-party-venues/tx/Dallas')
  get '/corporate-venues/tx/houston', to: redirect('http://venuecenter.com/corporate-event-venues/tx/houston')
  get '/corporate-venues/tx/Houston', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Houston')
  get '/corporate-party-venues/tx/Austin', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Austin')
  get '/corporate-party-venues/tx/Dallas', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Dallas')
  get '/corporate-party-venues/tx/Houston', to: redirect('http://venuecenter.com/corporate-event-venues/tx/Houston')
  get '/event-venues/:state/:city' => 'search#index', as: :city_search
  get '/:event_type-venues/:state/:city' => 'search#index', as: :event_type_search
  get '/tx/houston', to: redirect('/event-venues/tx/houston')
  get '/tx/dallas', to: redirect('/event-venues/tx/dallas')
  get '/tx/austin', to: redirect('/event-venues/tx/austin')
  get '/tx/fort-worth', to: redirect('/event-venues/tx/fort-worth')
  get '/event/:state/:city', to: redirect('/event-venues/%{state}/%{city}')
  get '/cities/:state/:city' => 'search#index'
  get '/search/confirm-submit' => 'search#confirm_submit'
  post '/search/get-info' => 'search#get_info', as: :search_get_info

  match '/search/:loc' => 'search#index', via: %i[get post], as: :search_loc
  match '/search' => 'search#index', via: %i[get post], as: :search

  resources :states

  get 'account' => 'account#index', as: :account_home

  get 'concierge' => 'concierge#index', as: :concierge_home
  get ':state/:city/:slug' => 'venue#index', as: :venue
  get 'venues/:slug' => 'venue#index', as: :old_venue
  get 'venues/not-found' => 'venue#not_found', as: :venue_not_found
  get 'about' => 'home#about'
  get 'how-it-works' => 'home#works'
  get 'faq' => 'home#faq'
  get 'contact' => 'home#contact'
  get 'tos' => 'home#tos'
  get 'privacy' => 'home#privacy'
  match 'process-contact' => 'home#processcontact', via: %i[get post]

  root 'home#index', as: :home

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home; end

  def index
    require 'rss'
    # @venue_types = VenueType.all()
    @cities = Venue.select('city, state_id').distinct.order(:city)
    # @event_types = EventType.all().order(:name)

    # Get blog items
    begin
      @blogs = RSS::Parser.parse(open('http://blog.venuecenter.com/feed').read, false).items[0..2]
    rescue StandardError
      @blogs = nil
    end
  end

  def about; end

  def faq; end

  def contact
    @contact_form = ContactForm.new
  end

  def tos; end

  def privacy; end

  def processcontact
    # Build hash from post parameters
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
      # Send mail to admin
      ContactMailer.contact_mailer(@contact_form).deliver_now
      # Go back to contact page with success message
      redirect_to :contact, notice: 'Your information was submitted. A member of our team will be in contact with you soon.'
    else
      render 'contact'
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :phone, :city, :state, :zip_code, :message)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<% content_for :page_title do %>
  About VenueCenter
<% end %>
<% content_for :page_description do %>
    VenueCenter is a one-stop shop for finding the perfect venue for your next event. With venues in Dallas, Houston, Austin, San Antonio and New Orleans, we can help you find 
a venue that meets your exact needs.
<% end %>
<% content_for :page_keywords do %>
 About VenueCenter, dallas event venues, austin event venues, houston event venues, san antonio event venues, new orleans event venues
<% end %>
<div class="container" style="margin-top: 30px; margin-bottom: 30px;">
  <div class="row">
    <div class="col-sm-12">
      <h1>About VenueCenter</h1>
      <p>
        VenueCenter is an online tool that helps people find the perfect venue to meet their needs! Our comprehensive online database provides an assortment of venue types all across the
        United States with pictures and amenities/features for each venue clearly displayed--we want to take the hassle out of the venue finding process and make the process more efficient.
      </p>  
      <p>We are headquartered in Dallas, Texas and started this business to be the go to source for venue selections no matter the event type. We applied all of our industry knowledge and
        know-how to identify the very best venues. We hope you enjoy!
      </p>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<% content_for :page_title do %>
  Contact VenueCenter for all your event planning needs
<% end %>
<% content_for :page_description do %>
  Contact VenueCenter for all your event planning needs
<% end %>

<div class="container" style="margin-top: 30px; margin-bottom: 30px;">
  <div class="row">
    <div class="col-sm-6">
      <div id="contact-image"></div>
      311 N Market St, Floor 2<br>
      Dallas, TX 75202<br>
      Phone: 214-308-2033<Br>
      Fax: 214-308-2044<br>
      Toll Free: (888) 511-2033<br>
      <%= mail_to 'hello@venuecenter.com' %>
    </div>
    <div class="col-sm-6">
      <h1>Contact Us</h1>
      <p>Need to get in contact with us? Fill out the form below and a member of our team will get back to you shortly.</p>
      <%= form_for @contact_form , url: '/process-contact' do |f|%>
      <% if !@contact_form.errors.empty? %>
          <div id="error_explanation">
            <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this request from being processed:</h2>
            <ul>
              <% @contact_form.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, { class: 'form-control', required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, { class: 'form-control', required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :phone, 'Phone Number' %>
          <%= f.text_field :phone, { class: 'form-control', required: true } %>
        </div>
        <div class="form-group">
          <div class="col-sm-6 npl">
            <%= f.label :city %>
            <%= f.text_field :city,{ class: 'form-control', required: true } %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-6 npl">
            <%= f.label :state %>
            <%= f.text_field :state, { class: 'form-control', required: true } %>
          </div>
        </div>
        
        <div class="form-group">
          <%= f.label :message, 'Message' %>
          <%= f.text_area :message, { class: 'form-control', required: true } %>
        </div>
        <div class="acenter">
          <input type="submit" value="Submit" class="btn btn-success">
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/home/faq.html.erb
<% content_for :page_title do %>
 Frequently Asked Questions
<% end %>
<% content_for :page_description do %>
  VenueCenter Frequently Asked Questions. Learn more about how VenueCenter works
<% end %>
<div class="container" style="margin-top: 30px;">
  <div class="row">
    <div class="col-sm-12">
      <h1 style="margin-bottom: 20px;">Frequently Asked Questions</h1>
      <h3>How can I create my own user account?</h3>
      <p>
        To create your own user account you must first click the sign up link. Once you are directed to the sign up page please enter the following: first and last name (required), email address (required), password and re-enter password (required). Once this registration form is finished please click submit. Our system will automatically send a verification email to confirm that all the information that you have entered is correct. After registration is complete you will be directed back to the home page.
      </p>
      <h3>How can I pay for additional services for my profile?</h3>
      <p>
        If you are a venue and would like to pay for additional enhancements to your profile page, please follow the steps to claim your venue by clicking here: <%= link_to 'Claim Venue', '/biz' %>.
      </p>
      <h3>How can I be sure viewers will be able to contact me?</h3>
      <p>
        To update, change, or remove information from your venue page please register and claim your venue by clicking here: <%= link_to 'Claim Venue', '/biz' %>.
      </p>
      <h3>I already have an account, but cannot log into my profile</h3>
      <p>
        Please follow the instructions to reset your password. If the problem persists please contact our customer service department for special instructions at <%= mail_to 'admin@venuecenter.com' %>.
      </p>
    </div><!-- .col-sm-12 -->
  </div><!-- .row -->
</div><!-- .container-fluid -->

app/views/home/index.html.erb
<% content_for :page_title do %>
  Find Venues for Weddings, Parties, Corporate Events, and more
<% end %>
<% content_for :page_description do %>
  VenueCenter has a collection of the best wedding venues, meeting rooms, unique venues, and corporate event venues to host your next event.
<% end %>
<% content_for :page_keywords do %>
  wedding venues, birthday party venues, find venues, corporate meeting venues, corporate event venues, unique venues, office space
<% end %>
<% content_for :page_head do %>
  <meta name="p:domain_verify" content="759c6ff80b5598242e5812f639e33080"/>
  <meta name="google-site-verification" content="wvPNs_RackG_FBmD5uGZj0RvSUfxFqoAPuq6nZa3Fn0" />
  <meta name='B-verify' content='abe9a111b381df77646f9f112f629685108f81ec' />
<% end %>


  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="height: 428px;">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            <li data-target="#carousel-example-generic" data-slide-to="5"></li>
            <li data-target="#carousel-example-generic" data-slide-to="6"></li>

          </ol><!-- .carousel-indicators -->

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197750/hm-1_ci92ca.jpg');">

              <div class="carousel-caption">

              </div>
            </div>
            <div class="item" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197749/hm-2_x01qyy.jpg');">
              <div class="carousel-caption">

              </div>
            </div>
            <div class="item" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197750/hm-3_pycdqc.jpg');">

              <div class="carousel-caption">

              </div>
            </div>
            <div class="item" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197750/hm-4_uahbig.jpg');">

              <div class="carousel-caption">

              </div>
            </div>
            <div class="item" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197750/hm-5_b8jnjx.jpg');">

              <div class="carousel-caption">

              </div>
            </div>
            <div class="item" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197751/hm-6_yx65m4.jpg');">

              <div class="carousel-caption">

              </div>
            </div>
            <div class="item" style="background-image: url('https://res.cloudinary.com/venuecenter/image/upload/v1443197752/hm-7_dslpkv.jpg');">

              <div class="carousel-caption">

              </div>
            </div>
          </div><!-- .carousel-inner -->

          <div class="container-fluid">
            <div class="row">
                <div class="col-xs-6 col-xs-offset-3 col-sm-8 col-sm-offset-2 home-search-form acenter">
                  <h1>Find the perfect venue for your next event</h1>
                    <%= form_tag("/search", method: "get", class: 'form-inline', role: 'form', id: 'searchForm') do %>
                      <div class="form-group">
                        <div class="input-group xs-mb-20">
                          <%= select_tag(:event_type, options_from_collection_for_select(EventType.order(:name), :slug, :name), { prompt: 'Event Type', class: 'form-control'}) %>
                        </div>
                        <div class="input-group xs-mb-20">
                          <%= text_field_tag(:loc, '', { class: 'form-control', placeholder: 'Location' }) %>
                        </div>
                        <div class="input-group xs-mb-20">
                          <%= number_field_tag(:g, nil, { placeholder: 'Number of Guests', class: 'form-control' }) %>
                        </div>
                        <input type="submit" value="Find My Venue" class="btn btn-success" style="font-weight: 600; height: 40px;">
                      </div>
                    <% end %>
                </div><!-- .home-search-form -->
            </div><!-- .row -->
          </div><!-- .container-fluid -->

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev" style="padding-top: 220px;">
            <span class="fa fa-chevron-left" aria-hidden="true" style="font-size: 20px;"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next" style="padding-top: 220px;">
            <span class="fa fa-chevron-right" aria-hidden="true" style="font-size: 20px;"></span>
            <span class="sr-only">Next</span>
          </a>

        </div><!-- .carousel-example-generic -->
  <div class="container">
    <div class="row" style="padding-top: 20px;">
      <div class="col-sm-12">
        <h2 class="home-special">It's as easy as 1-2-3</h2>
      </div><!-- .col-sm-12 -->
    </div><!-- .row -->
    <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
      <div class="col-xs-12 col-sm-4 home-3up">
        <i class="fa fa-search home-icon"></i><br>
        <h2 class="green">Search It</h2>
        <p>Search for venues by location, type, size and many more options.</p>
      </div><!-- .col-sm-4 -->
      <div class="col-xs-12 col-sm-4 home-3up">
        <i class="fa fa-usd home-icon"></i><br>
        <h2 class="green">Price It</h2>
        <p>Request a pricing quote from the venues that meet your criteria.</p>
      </div><!-- .col-sm-4 -->
      <div class="col-xs-12 col-sm-4 home-3up">
        <i class="fa fa-thumbs-up home-icon"></i><br>
        <h2 class="green">Book It</h2>
        <p>Work directly with the venue manager to book the space for your special event.</p>
      </div><!-- .col-sm-4 -->
    </div><!-- .row -->
  </div><!-- .container -->
  <div class="container-fluid" style="background: #000; margin-top: 20px;">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 acenter" style="color: #fff; font-size: 16px;">
          <!-- Begin MailChimp Signup Form -->
          <div id="mc_embed_signup">
            <form action="//venuecenter.us8.list-manage.com/subscribe/post?u=967795607eb167aa8a3cf34b3&amp;id=7b7c0440ed" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
              <div id="mc_embed_signup_scroll">
                <div class="form-group col-xs-12 col-sm-6" style="margin-top: 20px; display: inline-flex;">
                  <span class="acenter">Stay up to date with the latest VenueCenter news</span>
                </div>
                <div class="col-xs-12 col-sm-6 hm-newsletter-signup-fields">
                  <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Email Address" required style="
                   padding: 6px 12px; font-size: 14px; color: #000;">

                  <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-success hm-newsletter-join" style="border-radius: 0; margin: -1px 0 0 -5px;">

                  <div id="mce-responses">
                    <div class="response" id="mce-error-response" style="display:none"></div>
                    <div class="response" id="mce-success-response" style="display:none"></div>
                  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <div style="position: absolute; left: -5000px;"><input type="text" name="b_967795607eb167aa8a3cf34b3_7b7c0440ed" tabindex="-1" value=""></div>
                </div>
              </div>
            </form>
          </div>

          <!--End mc_embed_signup-->
        </div>
      </div>
    </div>
  </div>
  <div class="container" style="margin-top: 20px; padding-top: 20px; padding-bottom: 40px;">
    <div class="row">
      <div class="col-sm-12">
        <h2 class="home-section"><i class="fa fa-building"></i> Browse by City</h2>
        <div class="row">
          <div class="col-sm-12 col-md-4 acenter">
            <div class="home-cities austin">
              <%= link_to 'Austin', city_search_path(city: 'austin', state:'tx') %>
            </div>
          </div>
          <div class="col-sm-12 col-md-4 acenter">
            <div class="home-cities dallas">
              <%= link_to 'Dallas', city_search_path(city: 'dallas', state:'tx') %>
            </div>
          </div>
          <div class="col-sm-12 col-md-4 acenter">
            <div class="home-cities houston">
              <%= link_to 'Houston', city_search_path(city: 'houston', state:'tx') %>
            </div>
          </div>
        </div>
        <div class="col-sm-12 centered" style="margin: 20px 0;">
          <%= link_to 'See all cities we serve', cities_home_path, { style: 'font-size: 18px;'} %>
        </div>
      </div>
    </div><!-- .row -->
  </div><!-- .container -->
  <% if !@blogs.nil? %>
  <div class="container">
	<div class="row">
  	<div class="col-sm-12">
    	<h2 class="home-section"><i class="fa fa-rss-square"></i> Latest Articles</h2>
    	<div class="row">
      	<% @blogs.each do |blog| %>
        	<div class="col-sm-4 blog-post">

            	<div class="blog-content centered">
              	<%= blog.description.gsub("width:auto !important; max-width:50%; float:left;", "").html_safe %>

            	</div><!-- .blog-content -->
            	<h3 class="blog-title" style="font-size: 1.3em;"><%= link_to blog.title, blog.link %></h3>
        	</div><!-- .blog-post -->
      	<% end %>
    	</div><!-- .row -->
  	</div><!-- col-sm-12 -->
	</div><!-- .row -->
  </div><!-- .container -->
  <% end %>

app/views/home/works.html.erb
<% content_for :page_title do %>
  How It Works
<% end %>

<% content_for :page_description do %>
  How VenueCenter Works. VenueCenter is the fastest way to find the perfect venue for your next event.
<% end %>
<div class="container" style="margin-top: 30px;">
  <div class="row">
    <div class="col-sm-12">
      <h1>How It Works</h1>
      <p>
        VenueCenter is an online matching service that connects consumers to exceptional venues in their area.  Venues can
        create an account and be added to VenueCenter at any time.  Registered users may login to search and review venue
        profiles that meet their event requirements and users also have access to pictures, contact information, reviews and
        recommendations all in one place!   Search it. Price it. Book it.  Get started today!
      </p>
      <h3>Step 1</h3>
      <p>
        Sign up to get started and take control of your listing. We've spent countless hours and guzzled down several gallons of coffee scouring your area to add premium venues like yours to our database.
        While your venue may already be listed with us, we encourage you to register now to take full authority of your presence on our site. You're the expert on your venue, and we want you to be able to
        describe your venue to customers in ways that complement your brand!
      </p>
      <h3>Step 2</h3>
      <p>
          Update your listing and highlight what's great about your venue! Make sure your listing is accurate. Add contact information, business hours and other details that customers may need to know about
          your venue. Highlght what makes you unique. And of course, your listing would not be complete with a #VenueSelfie, so upload photos that give your venue personality and demonstrate how you help
          customers create lasting memories.
      </p>
      <p>
        As your VenueCenter property manager, you will have complete control of your page with the ability to:
        <ol>
          <li>Add photos, business hours, and other important information to help viewers access your venue details.</li>
          <li>Add other associated venues (when applicable)</li>
          <li>Track new customers and understand which search criteria were used to arrive at your venue profile.</li>
          <li>Respond to user reviews and requests for additional information.</li>
        </ol>
      </p>
      <h3>Step 3</h3>
      <p>
        Advertise to your target audience. By claiming your venue, we will help you build a larger customer base by identifying potential customers in your area.
        <ol>
          <li>Attract new customers by advertising on our homepage and stand out above the rest.</li>
          <li>Promote your business to customers and inform prospective customers about the benefits of your venue by allowing us to strategically promote to your targeted audience.</li>
          <li>Announce specials, discount promotions, or seasonal offers to drive additional business.*</li>
        </ol>
      </p>
      <p style="font-size: 12px;">
        * Updates are emailed to customers who have requested to receive email updates in your area.
      </p>

      <div class="acenter" style="margin: 20px auto;">
        <a href="/biz" class="btn btn-success btn-lg" style="color: #fff;">List Your Venue</a>
      </div>
   

    </div><!-- col-sm-12 -->
  </div><!-- .row -->
</div><!-- .container-fluid -->